/*
  File autogenerated by gengetopt version 2.22.6
  generated with the following command:
  /usr/bin/gengetopt --unamed-opts --output-dir=../../fontforge --file-name=sfddiff_opts 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef FIX_UNUSED
#define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
#endif

#include <getopt.h>

#include "sfddiff_opts.h"

const char *gengetopt_args_info_purpose = "Compare two font files.";

const char *gengetopt_args_info_usage = "Usage: sfddiff [OPTIONS]... FILE1 FILE2";

const char *gengetopt_args_info_versiontext = "";

const char *gengetopt_args_info_description = "";

const char *gengetopt_args_info_help[] = {
  "  -h, --help           Print help and exit",
  "  -V, --version        Print version and exit",
  "      --ignorehints    Do not compare PostScript hints or TrueType\n                         instructions.",
  "      --ignorenames    Do not compare font names.",
  "      --ignoregpos     Do not compare kerning, etc.",
  "      --ignoregsub     Do not compare ligatures, etc.",
  "      --ignorebitmaps  Do not compare bitmap strikes.",
  "      --exact          Normally sfddiff will match contours which are not exact\n                         but where the differences are slight (so you could\n                         compare TrueType and PostScript and get reasonable\n                         answers). Also normally sfddiff will unlink references\n                         before it compares (so you can compare a PostScript\n                         font [with no references] to the original source\n                         [which does have references]). Setting this flag means\n                         glyphs must match exactly.",
  "      --warn           Provide a warning when an exact match is not found.",
  "      --merge=STRING   Put any outline differences in the backgrounds of\n                         appropriate glyphs.",
    0
};

typedef enum {ARG_NO
  , ARG_STRING
} cmdline_parser_arg_type;

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error);


static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->ignorehints_given = 0 ;
  args_info->ignorenames_given = 0 ;
  args_info->ignoregpos_given = 0 ;
  args_info->ignoregsub_given = 0 ;
  args_info->ignorebitmaps_given = 0 ;
  args_info->exact_given = 0 ;
  args_info->warn_given = 0 ;
  args_info->merge_given = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  FIX_UNUSED (args_info);
  args_info->merge_arg = NULL;
  args_info->merge_orig = NULL;
  
}

static
void init_args_info(struct gengetopt_args_info *args_info)
{


  args_info->help_help = gengetopt_args_info_help[0] ;
  args_info->version_help = gengetopt_args_info_help[1] ;
  args_info->ignorehints_help = gengetopt_args_info_help[2] ;
  args_info->ignorenames_help = gengetopt_args_info_help[3] ;
  args_info->ignoregpos_help = gengetopt_args_info_help[4] ;
  args_info->ignoregsub_help = gengetopt_args_info_help[5] ;
  args_info->ignorebitmaps_help = gengetopt_args_info_help[6] ;
  args_info->exact_help = gengetopt_args_info_help[7] ;
  args_info->warn_help = gengetopt_args_info_help[8] ;
  args_info->merge_help = gengetopt_args_info_help[9] ;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n",
     (strlen(CMDLINE_PARSER_PACKAGE_NAME) ? CMDLINE_PARSER_PACKAGE_NAME : CMDLINE_PARSER_PACKAGE),
     CMDLINE_PARSER_VERSION);

  if (strlen(gengetopt_args_info_versiontext) > 0)
    printf("\n%s\n", gengetopt_args_info_versiontext);
}

static void print_help_common(void) {
  cmdline_parser_print_version ();

  if (strlen(gengetopt_args_info_purpose) > 0)
    printf("\n%s\n", gengetopt_args_info_purpose);

  if (strlen(gengetopt_args_info_usage) > 0)
    printf("\n%s\n", gengetopt_args_info_usage);

  printf("\n");

  if (strlen(gengetopt_args_info_description) > 0)
    printf("%s\n\n", gengetopt_args_info_description);
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);

  args_info->inputs = 0;
  args_info->inputs_num = 0;
}

void
cmdline_parser_params_init(struct cmdline_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct cmdline_parser_params *
cmdline_parser_params_create(void)
{
  struct cmdline_parser_params *params = 
    (struct cmdline_parser_params *)malloc(sizeof(struct cmdline_parser_params));
  cmdline_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}


static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{
  unsigned int i;
  free_string_field (&(args_info->merge_arg));
  free_string_field (&(args_info->merge_orig));
  
  
  for (i = 0; i < args_info->inputs_num; ++i)
    free (args_info->inputs [i]);

  if (args_info->inputs_num)
    free (args_info->inputs);

  clear_given (args_info);
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  FIX_UNUSED (values);
  if (arg) {
    fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}


int
cmdline_parser_dump(FILE *outfile, struct gengetopt_args_info *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", CMDLINE_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  if (args_info->ignorehints_given)
    write_into_file(outfile, "ignorehints", 0, 0 );
  if (args_info->ignorenames_given)
    write_into_file(outfile, "ignorenames", 0, 0 );
  if (args_info->ignoregpos_given)
    write_into_file(outfile, "ignoregpos", 0, 0 );
  if (args_info->ignoregsub_given)
    write_into_file(outfile, "ignoregsub", 0, 0 );
  if (args_info->ignorebitmaps_given)
    write_into_file(outfile, "ignorebitmaps", 0, 0 );
  if (args_info->exact_given)
    write_into_file(outfile, "exact", 0, 0 );
  if (args_info->warn_given)
    write_into_file(outfile, "warn", 0, 0 );
  if (args_info->merge_given)
    write_into_file(outfile, "merge", args_info->merge_orig, 0);
  

  i = EXIT_SUCCESS;
  return i;
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = cmdline_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = 0;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

int
cmdline_parser (int argc, char **argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser_ext (int argc, char **argv, struct gengetopt_args_info *args_info,
                   struct cmdline_parser_params *params)
{
  int result;
  result = cmdline_parser_internal (argc, argv, args_info, params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser2 (int argc, char **argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct cmdline_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = cmdline_parser_internal (argc, argv, args_info, &params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  FIX_UNUSED (args_info);
  FIX_UNUSED (prog_name);
  return EXIT_SUCCESS;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see cmdline_parser_params.check_ambiguity
 * @param override @see cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, const char *possible_values[],
               const char *default_value,
               cmdline_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;
  FIX_UNUSED (field);

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  FIX_UNUSED (default_value);
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };


  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}


int
cmdline_parser_internal (
  int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error_occurred = 0;
  struct gengetopt_args_info local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  override = params->override;
  initialize = params->initialize;
  check_required = params->check_required;
  check_ambiguity = params->check_ambiguity;

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "ignorehints",	0, NULL, 0 },
        { "ignorenames",	0, NULL, 0 },
        { "ignoregpos",	0, NULL, 0 },
        { "ignoregsub",	0, NULL, 0 },
        { "ignorebitmaps",	0, NULL, 0 },
        { "exact",	0, NULL, 0 },
        { "warn",	0, NULL, 0 },
        { "merge",	1, NULL, 0 },
        { 0,  0, 0, 0 }
      };

      c = getopt_long (argc, argv, "hV", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);


        case 0:	/* Long option with no short option */
          /* Do not compare PostScript hints or TrueType instructions..  */
          if (strcmp (long_options[option_index].name, "ignorehints") == 0)
          {
          
          
            if (update_arg( 0 , 
                 0 , &(args_info->ignorehints_given),
                &(local_args_info.ignorehints_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "ignorehints", '-',
                additional_error))
              goto failure;
          
          }
          /* Do not compare font names..  */
          else if (strcmp (long_options[option_index].name, "ignorenames") == 0)
          {
          
          
            if (update_arg( 0 , 
                 0 , &(args_info->ignorenames_given),
                &(local_args_info.ignorenames_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "ignorenames", '-',
                additional_error))
              goto failure;
          
          }
          /* Do not compare kerning, etc..  */
          else if (strcmp (long_options[option_index].name, "ignoregpos") == 0)
          {
          
          
            if (update_arg( 0 , 
                 0 , &(args_info->ignoregpos_given),
                &(local_args_info.ignoregpos_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "ignoregpos", '-',
                additional_error))
              goto failure;
          
          }
          /* Do not compare ligatures, etc..  */
          else if (strcmp (long_options[option_index].name, "ignoregsub") == 0)
          {
          
          
            if (update_arg( 0 , 
                 0 , &(args_info->ignoregsub_given),
                &(local_args_info.ignoregsub_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "ignoregsub", '-',
                additional_error))
              goto failure;
          
          }
          /* Do not compare bitmap strikes..  */
          else if (strcmp (long_options[option_index].name, "ignorebitmaps") == 0)
          {
          
          
            if (update_arg( 0 , 
                 0 , &(args_info->ignorebitmaps_given),
                &(local_args_info.ignorebitmaps_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "ignorebitmaps", '-',
                additional_error))
              goto failure;
          
          }
          /* Normally sfddiff will match contours which are not exact but where the differences are slight (so you could compare TrueType and PostScript and get reasonable answers). Also normally sfddiff will unlink references before it compares (so you can compare a PostScript font [with no references] to the original source [which does have references]). Setting this flag means glyphs must match exactly..  */
          else if (strcmp (long_options[option_index].name, "exact") == 0)
          {
          
          
            if (update_arg( 0 , 
                 0 , &(args_info->exact_given),
                &(local_args_info.exact_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "exact", '-',
                additional_error))
              goto failure;
          
          }
          /* Provide a warning when an exact match is not found..  */
          else if (strcmp (long_options[option_index].name, "warn") == 0)
          {
          
          
            if (update_arg( 0 , 
                 0 , &(args_info->warn_given),
                &(local_args_info.warn_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "warn", '-',
                additional_error))
              goto failure;
          
          }
          /* Put any outline differences in the backgrounds of appropriate glyphs..  */
          else if (strcmp (long_options[option_index].name, "merge") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->merge_arg), 
                 &(args_info->merge_orig), &(args_info->merge_given),
                &(local_args_info.merge_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "merge", '-',
                additional_error))
              goto failure;
          
          }
          
          break;
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */




  cmdline_parser_release (&local_args_info);

  if ( error_occurred )
    return (EXIT_FAILURE);

  if (optind < argc)
    {
      int i = 0 ;
      int found_prog_name = 0;
      /* whether program name, i.e., argv[0], is in the remaining args
         (this may happen with some implementations of getopt,
          but surely not with the one included by gengetopt) */

      i = optind;
      while (i < argc)
        if (argv[i++] == argv[0]) {
          found_prog_name = 1;
          break;
        }
      i = 0;

      args_info->inputs_num = argc - optind - found_prog_name;
      args_info->inputs =
        (char **)(malloc ((args_info->inputs_num)*sizeof(char *))) ;
      while (optind < argc)
        if (argv[optind++] != argv[0])
          args_info->inputs[ i++ ] = gengetopt_strdup (argv[optind-1]) ;
    }

  return 0;

failure:
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
