#! @GUILE@ \           -*- mode: bee; coding: utf-8 -*-
--no-auto-compile -s
!#

;; Copyright (C) 2012 Barry Schwartz
;; 
;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation; either version 3 of the License, or
;; (at your option) any later version.
;; 
;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.
;; 
;; You should have received a copy of the GNU General Public License
;; along with this program; if not, see <http://www.gnu.org/licenses/>.

(use-modules
   (ff-internal generate-types)
   (ice-9 format)
   (ice-9 match)
   (ice-9 receive)
   (ice-9 pretty-print)
   )

(receive (command-name module-name instruction-sources)
   (match (command-line)
      ((command-name module-name)
       (values command-name module-name (list (current-input-port))))
      ((command-name module-name . instruction-sources)
       (values command-name module-name instruction-sources))
      (_ (error "Expected command-line arguments: module-name instruction-sources")))
   (format #t ";; Generated by:\n")
   (format #t ";;\n")
   (format #t ";;    ~a \\\n" command-name)
   (format #t ";;       '~a' \\\n" module-name)
   (format #t ";;       '~a'\n" instruction-sources)
   (format #t ";;\n")
   (format #t "\n")
   (format #t "(define-module ~a)\n" module-name)
   (format #t "\n")
   (format #t "(use-modules (sortsmillff internal-types-syntax))\n")
   (format #t "\n")
   (let ((instructions (read-instruction-sources instruction-sources)))
      (pretty-print
         `(with-api-exported:--
             (api:--
                ,@(map underscores->hyphens instructions))))))
